<?php

namespace AppBundle\Repository;

/**
 * PastorLocalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PastorLocalRepository extends \Doctrine\ORM\EntityRepository
{
}
