<?php

namespace AppBundle\Repository;

/**
 * PresidenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresidenteRepository extends \Doctrine\ORM\EntityRepository
{
}
