<?php

namespace AppBundle\Repository;

/**
 * TesoreroLocalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TesoreroLocalRepository extends \Doctrine\ORM\EntityRepository
{
}
