<?php

namespace AppBundle\Repository;

/**
 * TesoreroNacionalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TesoreroNacionalRepository extends \Doctrine\ORM\EntityRepository
{
}
