# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    providers:
        our_db_provider:
            entity:
                class: AppBundle:Usuario
                property: dni

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            provider: our_db_provider
      
            form_login:
                login_path: login
                check_path: login
                always_use_default_target_path: true
                default_target_path: /presidente

            logout:
               path: /logout
               target: /login

    encoders:
        AppBundle\Entity\Usuario: 
            algorithm: bcrypt
    
    role_hierarchy:
        # admin is user too
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, roles: ROLE_USER }
        - { path: ^/presidente/*, roles: ROLE_ADMIN }
